[package]
name = "oth-regensburg-thesis"
version = "0.1.0"
entrypoint = "template/lib.typ"
authors = [
    "Robert Richter <https://github.com/judgeNotFound>",
    "Felix Hoffmann <https://github.com/felixhoffmnn>",
    "Korbinian Hutter <https://github.com/korbinianhutter>",
]
license = "MIT"
disciplines = [
    "computer-science",
    "artificial-intelligence",
    "engineering",
    "mathematics",
    "medicine",
    "business",
]
description = "A clean thesis template for Bachelor's and Master's theses at OTH Regensburg."
repository = "https://github.com/felixhoffmnn/oth-thesis-template"
keywords = [
    "OTH",
    "OTH Regensburg",
    "OTH-Regensburg",
    "Ostbayerische Technische Hochschule",
    "Ostbayerische Technische Hochschule Regensburg",
    "University of Regensburg",
    "Bachelor's thesis",
    "Master's thesis",
    "Bachelorsthesis",
    "Mastersthesis",
    "Bachelorthesis",
    "Masterthesis",
    "Bachelorarbeit",
    "Masterarbeit",
    "thesis",
]
categories = ["thesis"]
compiler = "0.14.0"
exclude = ["example/main.pdf"]

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
